'use client';
import {useState} from 'react';
import {ArrowUpRight, Menu, X, Check, Send, Phone, MapPin, ChevronDown} from 'lucide-react';
import './page.css';

type Product={id:string; name:string; desc:string; price:number; kind:'sheet'|'crumb'; tone:string; icon:string};
const densities=[7,10,12,14,15,16,18,20], thicknesses=[1,2,3,5,10,15,20,30,40,50,60];
const products:Product[]=[
 {id:'white',name:'OQ PENAPLAST',desc:'Turli qurilish va issiqlik izolyatsiyasi ishlari uchun sifatli EPS penaplast.',price:67,kind:'sheet',tone:'white',icon:'▦'},
 {id:'black',name:'QORA PENAPLAST',desc:'Qurilish va izolyatsiya ishlari uchun sifatli qora EPS penaplast.',price:67,kind:'sheet',tone:'black',icon:'▦'},
 {id:'crumb',name:'MAYDALANGAN PENAPLAST',desc:'Qadoqlash va izolyatsiya uchun yengil, qulay va tejamkor yechim.',price:.70,kind:'crumb',tone:'crumb',icon:'✣'}
];
const priceMap:Record<number,number>={7:32,10:40,12:50,14:62,15:67,16:71,18:79,20:87};
const nav=[['Bosh sahifa','home'],['Mahsulotlar','products'],['Ishlab chiqarish','production'],['Nega Penaplast','advantages'],['Qayerda ishlatiladi','applications'],['Biz haqimizda','about'],['Aloqa','contact']];
export default function Page(){
 const [menu,setMenu]=useState(false); const [order,setOrder]=useState<Product|null>(null); const [density,setDensity]=useState(15); const [thickness,setThickness]=useState(10); const [qty,setQty]=useState(1); const [sent,setSent]=useState(false);
 const open=(p:Product)=>{setOrder(p);setSent(false)};
 const current=order?.kind==='crumb'?qty*.7:priceMap[density];
 return <main><header><a className="brand" href="#home"><span>IZO <b>PLUS</b></span><small>PENAPLAST ZAVODI</small></a><nav>{nav.map(([x,id])=><a key={id} href={'#'+id}>{x}</a>)}</nav><button className="top-cta" onClick={()=>open(products[0])}>BUYURTMA BERISH <ArrowUpRight size={16}/></button><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{menu&&<div className="mobile-nav">{nav.map(([x,id])=><a onClick={()=>setMenu(false)} href={'#'+id} key={id}>{x}</a>)}</div>}
 <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow"><i/> IZO PLUS / 1998 YILDAN BERI</p><h1>SIFATLI<br/><em>PENAPLAST.</em><br/>ISHONCHLI QURILISH.</h1><p className="lead">Qurilish, issiqlik izolyatsiyasi va sanoat uchun sifatli EPS penaplast mahsulotlari.</p><div className="actions"><a className="button primary" href="#products">MAHSULOTLARNI KO‘RISH <ArrowUpRight size={18}/></a><button className="button ghost" onClick={()=>open(products[0])}>BUYURTMA BERISH</button></div></div><div className="hero-art"><div className="grid-lines"/><div className="foam foam-a"/><div className="foam foam-b"/><div className="foam foam-c"/><span className="art-label">EPS / 01<br/><b>PRECISION<br/>IN EVERY LAYER</b></span></div></section>
 <section className="stats"><div><b>25+</b><span>YILLIK TAJRIBA</span></div><div><b>3</b><span>ASOSIY MAHSULOT</span></div><div><b>7–20</b><span>KG/M³ ZICHLIG</span></div><div><b>1–60</b><span>CM QALINLIK</span></div></section>
 <section id="products" className="section products"><div className="section-head"><div><p className="eyebrow">01 / MAHSULOTLAR</p><h2>Sizga kerakli<br/><em>yechim.</em></h2></div><p className="section-note">Har bir loyiha uchun aniq o‘lcham, ishonchli sifat va tezkor buyurtma.</p></div><div className="product-grid">{products.map(p=><article className={'product-card '+p.tone} key={p.id}><div className="product-visual"><span className="product-number">0{products.indexOf(p)+1}</span><div className="product-shape"><span>{p.icon}</span></div><span className="product-code">PENAPLAST / {p.id.toUpperCase()}</span></div><div className="product-body"><h3>{p.name}</h3><p>{p.desc}</p>{p.kind==='sheet'?<><label>ZICHLIGI <small>KG/M³</small></label><div className="chips">{densities.map(d=><button className={density===d?'selected':''} onClick={()=>setDensity(d)} key={d}>{d}</button>)}</div><label>QALINLIGI <small>CM</small></label><div className="chips thick">{thicknesses.map(t=><button className={thickness===t?'selected':''} onClick={()=>setThickness(t)} key={t}>{t}</button>)}</div></>:<><label>MIQDORI <small>KG</small></label><input className="qty" type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))}/></>}<div className="price-row"><div><small>NARX</small><strong>${p.kind==='crumb'?current.toFixed(2):priceMap[density]}</strong>{p.kind==='crumb'&&<small>/ KG</small>}</div><button className="order-btn" onClick={()=>open(p)}>BUYURTMA <ArrowUpRight size={17}/></button></div></div></article>)}</div></section>
 <section id="production" className="dark-section"><div className="section-head"><div><p className="eyebrow">02 / ISHLAB CHIQARISH</p><h2>Sifat — bu<br/><em>jarayon.</em></h2></div></div><div className="process">{['XOMASHYO','KO‘PIRTIRISH','QOLIPLASH','KESISH','SIFAT NAZORATI','TAYYOR MAHSULOT'].map((x,i)=><div className="process-item" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{['Yuqori sifatli xomashyolarni tanlaymiz.','Zarralarni aniq hajmda ko‘pirtiramiz.','Mustahkam va tekis bloklar hosil qilamiz.','Har bir o‘lchamni aniqlik bilan kesamiz.','Har bir partiya nazoratdan o‘tadi.','Yetkazib berishga tayyor mahsulot.'][i]}</p></div>)}</div></section>
 <section id="advantages" className="section"><div className="section-head"><div><p className="eyebrow">03 / NЕGA PENAPLAST</p><h2>Har qatlamda<br/><em>ishonch.</em></h2></div></div><div className="adv-grid">{['YUQORI SIFAT','ANIQ ZICHLIG','TURLI QALINLIK','ISSIQLIK IZOLYATSIYASI','ISHONCHLI ISHLAB CHIQARISH','TEZKOR BUYURTMA'].map((x,i)=><div className="adv" key={x}><span>0{i+1}</span><Check size={20}/><h3>{x}</h3><p>Professional loyihalar uchun o‘ylangan, sinovdan o‘tgan yechim.</p></div>)}</div></section>
 <section id="applications" className="applications"><div><p className="eyebrow">04 / QAYERDA ISHLATILADI</p><h2>Chegarasiz<br/><em>imkoniyatlar.</em></h2></div><div className="app-list">{['Uy-joy qurilishi','Devor izolyatsiyasi','Tom izolyatsiyasi','Pol izolyatsiyasi','Sanoat','Sovutish tizimlari','Qadoqlash'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span><ArrowUpRight size={20}/></div>)}</div></section>
 <section id="about" className="about"><div className="about-mark">IZO<br/><b>PLUS</b></div><div><p className="eyebrow">05 / BIZ HAQIMIZDA</p><h2>IZO PLUS —<br/><em>Penaplast Zavodi.</em></h2><p>Qurilish, issiqlik izolyatsiyasi va sanoat uchun sifatli EPS penaplast mahsulotlarini ishlab chiqaramiz.</p><a href="#contact" className="text-link">BIZ BILAN BOG‘LANING <ArrowUpRight size={17}/></a></div></section>
 <section id="contact" className="contact"><p className="eyebrow">06 / ALOQA</p><h2>Loyihangizni<br/><em>boshlaymiz.</em></h2><div className="contact-row"><a href="tel:+9989951322222"><Phone/> +998 99 513 22 22</a><a href="https://t.me/penaplast_uz"><Send/> @penaplast_uz</a><button className="button primary" onClick={()=>open(products[0])}>BUYURTMA BERISH <ArrowUpRight size={18}/></button></div></section>
 <footer><a className="brand" href="#home"><span>IZO <b>PLUS</b></span><small>PENAPLAST ZAVODI</small></a><div>© 2026 IZO PLUS. Barcha huquqlar himoyalangan.</div><a href="https://t.me/penaplast_uz">TELEGRAM ↗</a></footer>
 {order&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setOrder(null)}><div className="modal"><button className="close" onClick={()=>setOrder(null)}><X/></button>{sent?<div className="success"><div><Check/></div><h2>Buyurtmangiz muvaffaqiyatli yuborildi!</h2><p>Tez orada operatorimiz siz bilan bog‘lanadi.</p><a className="button primary" href="https://t.me/penaplast_uz">TELEGRAMGA O‘TISH <ArrowUpRight/></a></div>:<><p className="eyebrow">BUYURTMA / 01</p><h2>Buyurtma<br/><em>berish.</em></h2><div className="order-summary"><div className={'mini '+order.tone}/><div><b>{order.name}</b><span>{order.kind==='crumb'?`${qty} KG`:`${density} KG/M³ · ${thickness} CM`}</span></div><strong>${current.toFixed(2)}</strong></div><form onSubmit={e=>{e.preventDefault(); const f=new FormData(e.currentTarget); const msg=`YANGI BUYURTMA%0A%0AMahsulot: ${order.name}%0A${order.kind==='crumb'?`Miqdor: ${qty} KG`:`Zichlik: ${density} kg/m³%0AQalinlik: ${thickness} cm`}%0ANarx: $${current.toFixed(2)}%0A%0AMIJOZ:%0AIsm: ${f.get('name')}%0ATelefon: ${f.get('phone')}%0AManzil: ${f.get('address')}%0AIzoh: ${f.get('note')||'-'}`; window.open(`https://t.me/penaplast_uz?text=${msg}`,'_blank'); setSent(true)}}><input name="name" required placeholder="Ismingiz *"/><input name="phone" required pattern="[+]?[0-9 ()-]{9,}" placeholder="Telefon raqamingiz *"/><input name="address" required placeholder="Manzilingiz *"/><textarea name="note" placeholder="Qo‘shimcha izoh" rows={3}/><button className="button primary full">BUYURTMA YUBORISH <Send size={17}/></button><small className="privacy">Ma’lumotlaringiz xavfsiz saqlanadi.</small></form></>}</div></div>}</main>
}
